# Generated by Django 5.1.4 on 2025-03-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_subscription_follower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_banners/"
            ),
        ),
    ]
