# Generated by Django 5.1.4 on 2025-02-19 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_options_save"),
    ]

    operations = [
        migrations.AlterField(
            model_name="save",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saves",
                to="blog.blogpost",
            ),
        ),
    ]
