# Generated by Django 5.1.4 on 2025-03-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
